name: flutter_valper
description: A smart parking app for Samar State University.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  camera: ^0.10.5+9
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  path: ^1.8.3
  supabase_flutter: ^2.5.1
  url_launcher: ^6.2.6
  supabase_auth_ui: ^0.5.5
  intl: ^0.18.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^6.0.0
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  image: ^4.1.3
  video_player: ^2.8.2
  image_picker: ^1.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/ssu_logo.png
    - assets/back.png
    - assets/google.png
    - assets/facebook.png
    - assets/valper_logo.png
    - assets/home.png
    - assets/records.png
    - assets/parking.png
    - assets/support.png
    - assets/information.png
    - assets/register.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
